store/urls.py
from django.urls import path
from . import views

app_name = "store"

urlpatterns = [
    path('', views.index, name='index'),
    path('micro', views.micro, name='micro'),
    path('haem', views.haem, name='haem'),
    path('chem', views.chem, name='chem'),
    path('histo', views.histo, name='histo'),
    path('history/<int:pk>', views.history, name='history'),
    path('itemHistory/<int:pk>/<str:slug>', views.ItemHistory, name='itemHistory'),
    path('newstock', views.newstock, name='newstock'),
    path('delete/<str:slug>', views.delete, name='delete'),
    path('login', views.login, name='login'),
    path("logout", views.logout, name="logout"),
]

store_management_app/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls'))
]

templates/dept1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link href="{% static './css/dept1.css' %}" rel="stylesheet">
    
</head>

<body>
    <header>
        <h1>Store Management App</h1>
    </header>
    <main>
        <!-- <section class="side_nav">
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">dept 1</a></li>
                <li><a href="#">dept 2</a></li>
                <li><a href="#">dept 3</a></li>
                <li><a href="#">dept 4</a></li>
            </ul>
        </section> -->

        <section class="hero">


            <div class="dept_nav">
                <a href="/"><span>Home</span></a>
                <a href="/micro"><span  class="active">Micro</span></a>
                <a href="/haem"><span>Haem</span></a>
                <a href="/chem"><span>Chem path</span></a>
                <a href="/histo"><span>Histo</span></a>
            </div>

            <div class="card_wrapper">
                {% for message in messages %}
                <h5 style="color: red;">{{message}}</h5> 
                {% endfor %}
                <div class="header_div">
                    <h3>items</h3>
                    <div class="wrapper">
                        <button onclick="handleNewStock()">+ New Stock</button>
                        <a href="history/1"><img src="{% static './assets/Calendar.svg'%}" alt=""></a>
                    
                    </div>
                </div>

                <div class="items_wrapper">

                    <table>
                        <thead>
                            <tr>
                                <th>Item name</th>
                                <th>Amount in store</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for item in items %}
                                
                                {% if item.dept.dept_name == "micro" %}
                                    
                                    <tr>
                                        <td><a class="name" href="itemHistory/1/{{item.slug}}">{{item.item_name}}</a></td>
                                        <td>{{item.amount}}</td>
                                        <td><button onclick="showModal('{{item.item_name}}')">add/subtract</button></td>
                                        <td class="remove"><a href="/delete/{{ item.slug }}"><img src="{% static './assets/deleteIcon.svg' %}" alt=""></a></td>
                                    </tr>
                                   
                                {% endif %}
                            {% endfor %}
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </section>
    </main>

    <footer>
        <Span>Forklift &copy2023</Span>
    </footer>

    <div class="background_wrapper">

    </div>

    <div class="modal_container">
        <form method="post" action="micro">
            {% csrf_token %}
            <input id="modalNameInput" type="text" name="input_name" value="Paracetamol">
            <input type="number" name="input_amount" placeholder="amount">
            <select name="op_type" id="">
                <option value="add">add</option>
                <option value="subtract">subtract</option>
            </select>
            <button>submit</button>
        </form>
        <button id="cancelBtn" class="cancel_btn" onclick="closeModal()">cancel</button>
    </div>

    <div class="new_stock">
        <form method="post" action="newstock">
            {% csrf_token %}
            <input id="modalNameInput" type="text" name="item_name" placeholder="Item name">
            <input type="number" name="item_amount" placeholder="amount">
            <select name="dept" id="">
                <option value="micro">micro</option>
            </select>
            <button>submit</button>
        </form>
        <button id="cancelNewStock" class="cancel_btn" onclick="closeNewStockModal()">cancel</button>
    </div>
    <script src="{% static './js/dept1.js' %}"></script>
</body>

</html>

templates/dept2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link href="{% static './css/dept1.css' %}" rel="stylesheet">

</head>

<body>
    <header>
        <h1>Store Management App</h1>
    </header>
    <main>
        <!-- <section class="side_nav">
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">dept 1</a></li>
                <li><a href="#">dept 2</a></li>
                <li><a href="#">dept 3</a></li>
                <li><a href="#">dept 4</a></li>
            </ul>
        </section> -->

        <section class="hero">


            <div class="dept_nav">
                <a href="/"><span>Home</span></a>
                <a href="/micro"><span>Micro</span></a>
                <a href="/haem"><span class="active">Haem</span></a>
                <a href="/chem"><span>Chem path</span></a>
                <a href="/histo"><span>Histo</span></a>
            </div>

            <div class="card_wrapper">
                {% for message in messages %}
                <h5 style="color: red;">{{message}}</h5>
                {% endfor %}
                <div class="header_div">
                    <h3>items</h3>
                    <div class="wrapper">
                        <button onclick="handleNewStock()">+ New Stock</button>
                        <a href="history/2"><img src="{% static './assets/Calendar.svg'%}" alt=""></a>
                    
                    </div>
                </div>

                <div class="items_wrapper">

                    <table>
                        <thead>
                            <tr>
                                <th>Item name</th>
                                <th>Amount in store</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for item in items %}

                            {% if item.dept.dept_name == "haem" %}
                                <tr>
                                    <td><a class="name" href="itemHistory/2/{{item.slug}}">{{item.item_name}}</a></td>
                                    <td>{{item.amount}}</td>
                                    <td><button onclick="showModal('{{item.item_name}}')">add/subtract</button></td>
                                    <td class="remove"><a href="/delete/{{ item.slug }}"><img src="{% static './assets/deleteIcon.svg' %}" alt=""></a></td>
                                </tr>
                            {% endif %}
                            {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </section>
    </main>

    <footer>
        <Span>Forklift &copy2023</Span>
    </footer>

    <div class="background_wrapper">

    </div>

    <div class="modal_container">
        <form method="post" action="{% url 'store:haem' %}">
            {% csrf_token %}
            <input id="modalNameInput" type="text" name="input_name" value="Paracetamol">
            <input type="number" name="input_amount" placeholder="amount">
            <select name="op_type" id="">
                <option value="add">add</option>
                <option value="subtract">subtract</option>
            </select>
            <button>submit</button>
        </form>
        <button id="cancelBtn" class="cancel_btn" onclick="closeModal()">cancel</button>
    </div>

    <div class="new_stock">
        <form method="post" action="{% url 'store:newstock' %}">
            {% csrf_token %}
            <input id="modalNameInput" type="text" name="item_name" placeholder="Item name">
            <input type="number" name="item_amount" placeholder="amount">
            <select name="dept" id="">
                <option value="haem">haem</option>
            </select>
            <button>submit</button>
        </form>
        <button id="cancelNewStock" class="cancel_btn" onclick="closeNewStockModal()">cancel</button>
    </div>
    <script src="{% static './js/dept1.js' %}"></script>
</body>

</html>

templates/dept3.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link href="{% static './css/dept1.css' %}" rel="stylesheet">

</head>

<body>
    <header>
        <h1>Store Management App</h1>
    </header>
    <main>
        <!-- <section class="side_nav">
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">dept 1</a></li>
                <li><a href="#">dept 2</a></li>
                <li><a href="#">dept 3</a></li>
                <li><a href="#">dept 4</a></li>
            </ul>
        </section> -->

        <section class="hero">


            <div class="dept_nav">
                <a href="/"><span>Home</span></a>
                <a href="/micro"><span>Micro</span></a>
                <a href="/haem"><span>haem</span></a>
                <a href="/chem"><span class="active">Chem path</span></a>
                <a href="/histo"><span>Histo</span></a>
            </div>

            <div class="card_wrapper">
                {% for message in messages %}
                <h5 style="color: red;">{{message}}</h5>
                {% endfor %}
                <div class="header_div">
                    <h3>items</h3>
                    <div class="wrapper">
                        <button onclick="handleNewStock()">+ New Stock</button>
                        <a href="history/3"><img src="{% static './assets/Calendar.svg'%}" alt=""></a>
                    
                    </div>
                </div>

                <div class="items_wrapper">

                    <table>
                        <thead>
                            <tr>
                                <th>Item name</th>
                                <th>Amount in store</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for item in items %}

                            {% if item.dept.dept_name == "chem" %}
                                <tr>
                                    <td><a class="name" href="itemHistory/3/{{item.slug}}">{{item.item_name}}</a></td>
                                    <td>{{item.amount}}</td>
                                    <td><button onclick="showModal('{{item.item_name}}')">add/subtract</button></td>
                                    <td class="remove"><a href="/delete/{{ item.slug }}"><img src="{% static './assets/deleteIcon.svg' %}" alt=""></a></td>
                                </tr>
                            {% endif %}
                            {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </section>
    </main>

    <footer>
        <Span>Forklift &copy2023</Span>
    </footer>

    <div class="background_wrapper">

    </div>

    <div class="modal_container">
        <form method="post" action="chem">
            {% csrf_token %}
            <input id="modalNameInput" type="text" name="input_name" value="Paracetamol">
            <input type="number" name="input_amount" placeholder="amount">
            <select name="op_type" id="">
                <option value="add">add</option>
                <option value="subtract">subtract</option>
            </select>
            <button>submit</button>
        </form>
        <button id="cancelBtn" class="cancel_btn" onclick="closeModal()">cancel</button>
    </div>

    <div class="new_stock">
        <form method="post" action="newstock">
            {% csrf_token %}
            <input id="modalNameInput" type="text" name="item_name" placeholder="Item name">
            <input type="number" name="item_amount" placeholder="amount">
            <select name="dept" id="">
                <option value="chem">chem</option>
            </select>
            <button>submit</button>
        </form>
        <button id="cancelNewStock" class="cancel_btn" onclick="closeNewStockModal()">cancel</button>
    </div>
    <script src="{% static './js/dept1.js' %}"></script>
</body>

</html>

templates/dept4.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link href="{% static './css/dept1.css' %}" rel="stylesheet">

</head>

<body>
    <header>
        <h1>Store Management App</h1>
    </header>
    <main>
        <!-- <section class="side_nav">
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">dept 1</a></li>
                <li><a href="#">dept 2</a></li>
                <li><a href="#">dept 3</a></li>
                <li><a href="#">dept 4</a></li>
            </ul>
        </section> -->

        <section class="hero">


            <div class="dept_nav">
                <a href="/"><span>Home</span></a>
                <a href="/micro"><span>Micro</span></a>
                <a href="/haem"><span>Haem</span></a>
                <a href="/chem"><span>Chem path</span></a>
                <a href="/histo"><span class="active">Histo</span></a>
            </div>

            <div class="card_wrapper">
                {% for message in messages %}
                <h5 style="color: red;">{{message}}</h5>
                {% endfor %}
                <div class="header_div">
                    <h3>items</h3>
                    <div class="wrapper">
                        <button onclick="handleNewStock()">+ New Stock</button>
                        <a href="history/4"><img src="{% static './assets/Calendar.svg'%}" alt=""></a>
                        
                    </div>
                </div>

                <div class="items_wrapper">

                    <table>
                        <thead>
                            <tr>
                                <th>Item name</th>
                                <th>Amount in store</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for item in items %}

                            {% if item.dept.dept_name == "histo" %}
                                <tr>
                                    <td><a class="name" href="itemHistory/4/{{item.slug}}">{{item.item_name}}</a></td>
                                    <td>{{item.amount}}</td>
                                    <td><button onclick="showModal('{{item.item_name}}')">add/subtract</button></td>
                                    <td class="remove"><a href="/delete/{{ item.slug }}"><img src="{% static './assets/deleteIcon.svg' %}" alt=""></a></td>
                                </tr>
                            {% endif %}
                            {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </section>
    </main>

    <footer>
        <Span>Forklift &copy2023</Span>
    </footer>

    <div class="background_wrapper">

    </div>

    <div class="modal_container">
        <form method="post" action="histo">
            {% csrf_token %}
            <input id="modalNameInput" type="text" name="input_name" value="Paracetamol">
            <input type="number" name="input_amount" placeholder="amount">
            <select name="op_type" id="">
                <option value="add">add</option>
                <option value="subtract">subtract</option>
            </select>
            <button>submit</button>
        </form>
        <button id="cancelBtn" class="cancel_btn" onclick="closeModal()">cancel</button>
    </div>

    <div class="new_stock">
        <form method="post" action="newstock">
            {% csrf_token %}
            <input id="modalNameInput" type="text" name="item_name" placeholder="Item name">
            <input type="number" name="item_amount" placeholder="amount">
            <select name="dept" id="">
                <option value="histo">histo</option>
            </select>
            <button>submit</button>
        </form>
        <button id="cancelNewStock" class="cancel_btn" onclick="closeNewStockModal()">cancel</button>
    </div>
    <script src="{% static './js/dept1.js' %}"></script>
</body>

</html>

templates/history.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>History</title>

    <link href="{% static './css/history.css' %}" rel="stylesheet">

</head>

<body>
    <header>
        <h1>Store Management App</h1>
        <span>logged in</span>
    </header>
    <main>
        <!-- <section class="side_nav">
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">dept 1</a></li>
                <li><a href="#">dept 2</a></li>
                <li><a href="#">dept 3</a></li>
                <li><a href="#">dept 4</a></li>
            </ul>
        </section> -->

        <section class="hero">


            <!-- <div class="dept_nav">
                <a href="/"><span>Home</span></a>
                <a href="/dept1"><span class="active">dept 1</span></a>
                <a href="/dept2"><span>dept 2</span></a>
                <a href="/dept3"><span>dept 3</span></a>
                <a href="/dept4"><span>dept 4</span></a>
            </div> -->

            <div class="card_wrapper">

                <div class="header_div">
                    <h3>History</h3>
                </div>

                <div class="items_wrapper">

                    <table>
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Item</th>
                                <th>Amount</th>
                                <th>Balance</th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for hist in history %}
                                <tr>
                                    <td>{{hist.date_created}}</td>
                                    <td>{{hist.item_name}}</td>
                                    <td>{{hist.amount}}</td>
                                    <td>{{hist.bal}}</td>
                                </tr>
                            {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </section>
    </main>

    <footer>
        <Span>Forklift &copy2023</Span>
    </footer>

    <!-- <div class="background_wrapper">

    </div>

    <div class="modal_container">
        <form method="post" action="dept1">
            {% csrf_token %}
            <input id="modalNameInput" type="text" name="input_name" value="Paracetamol">
            <input type="number" name="input_amount" placeholder="amount">
            <select name="op_type" id="">
                <option value="add">add</option>
                <option value="subtract">subtract</option>
            </select>
            <button>submit</button>
        </form>
        <button id="cancelBtn" class="cancel_btn" onclick="closeModal()">cancel</button>
    </div>

    <div class="new_stock">
        <form method="post" action="newstock">
            {% csrf_token %}
            <input id="modalNameInput" type="text" name="item_name" placeholder="Item name">
            <input type="number" name="item_amount" placeholder="amount">
            <select name="dept" id="">
                <option value="dept1">dept1</option>
            </select>
            <button>submit</button>
        </form>
        <button id="cancelNewStock" class="cancel_btn" onclick="closeNewStockModal()">cancel</button>
    </div> -->
    <script src="{% static './js/history.js' %}"></script>
</body>

</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link href="{% static './css/style.css' %}" rel="stylesheet">
</head>

<body>
    <header>
        <h1>Store Management App</h1>
        {% if user.is_authenticated %}
        <span><a href="{% url 'store:logout' %}">logout</a></span>
        {% else %}
        <span><a href="{% url 'store:login' %}">login</a></span>
        {% endif %}
    </header>
    <main>
        <!-- <section class="side_nav">
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">dept 1</a></li>
                <li><a href="#">dept 2</a></li>
                <li><a href="#">dept 3</a></li>
                <li><a href="#">dept 4</a></li>
            </ul>
        </section> -->

        <section class="hero">


            <div class="dept_nav">
                <a href="/"><span class="active1">Home</span></a>
                <a href="/micro"><span>Micro</span></a>
                <a href="/haem"><span>Haem</span></a>
                <a href="/chem"><span>Chem</span></a>
                <a href="/histo"><span>Histo</span></a>
            </div>

            <div class="card_wrapper">

                <div class="card">
                    <p>Microbiology / Parasitology</p>
                    <span>No of items: <i>{{dept1}}</i></span>
                </div>

                <div class="card">
                    <p>Haematology / Seratology</p>
                    <span>No of items: <i>{{dept2}}</i></span>
                </div>

                <div class="card">
                    <p>Chemical Pathology</p>
                    <span>No of items: <i>{{dept3}}</i></span>
                </div>

                <div class="card">
                    <p>Histopathology</p>
                    <span>No of items: <i>{{dept4}}</i></span>
                </div>
            </div>
        </section>
    </main>

    <footer>
        <Span>Forklift &copy2023</Span>
    </footer>

    
</body>

</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link href="{% static './css/login.css' %}" rel="stylesheet">
</head>

<body>
    <header>
        <h1>Store Management App</h1>
        <span>login</span>
    </header>
    <main>
        <form method="post" action="login">
            {% csrf_token %}
            <label for="username">Username</label>
            <input placeholder="username" name="username" type="text">
            <label for="password">Password</label>
            <input type="password" name="password" id="">
            <button>submit</button>
        </form>
        
    </main>

    <footer>
        <Span>Forklift &copy2023</Span>
    </footer>


</body>

</html>